### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by yarons** [gpodder/mygpo#123]
https://github.com/gpodder/mygpo/blob/4b4ea55fb7185d6fab8c96ca14a9d6ec36dbaaa9/mygpo/users/templates/registration/resent_activation.html#L11

I think it's supposed to be "resent", otherwise it's pretty confusing.

**Comment by yarons** [comment]
Proposed fix in #124.

**Comment by stefankoegl** [comment]
Closed by #124
