### ISSUE TITLE
admin-ui  -  can't save podcast nullable field without value.

### ISSUE THREAD

**Issue by roadt** [gpodder/mygpo#162]
![image](https://user-images.githubusercontent.com/149592/47318544-ec17b480-d67e-11e8-9916-cdb0c438a9e1.png)

The podcast is imported from /missing,   open it in admin-ui , and click save.  It reports errors.

**Comment by roadt** [comment]
@stefankoegl    

Hi, I created quick fix.   #163 

change _blank_ field to True (as django admin use it as 'required' flag),  and still keep null=True  for   _xxx__isnull_  checks.

**Comment by stefankoegl** [comment]
#163 has been merged - thanks!
