### ISSUE TITLE
API: add a fully-functioning device without using web ui

### ISSUE THREAD

**Issue by JBuursma** [gpodder/mygpo#207]
Is this possible? I have a gpodder.net account, but when I install AntennaPod on a new device and enter my gpodder.net credentials, it appears to connect, but it doesn't sync anything. I have to go to https://gpodder.net/devices/ and set up the sync settings -- then everything works. My question is this: is that last step really necessary? Can't a sane default be chosen so that all you need to do from AntennaPod is enter your credentials and everything works? Most people would want two-way sync of all their podcasts.

This is a stumbling block for new users. People already familiar with gpodder.net know that this is the drill. For everyone else, the sync just won't work right and they'll be mystified as to why.

If there is no way to make this more frictionless for the user, then a workaround might be more helpful messages in AntennaPod. 

In general, thank you for a great service -- I'm thrilled to have an open-source alternative to iTunes for podcasting!

**Comment by stefankoegl** [comment]
From the perspective of gpodder.net, a new device is created when it is first used. AntennaPod would just have to create some device ID and include it in the requests. 

It seems that this would be best addressed in AntennaPod.

**Comment by stefankoegl** [comment]
I'm closing this as the question seems to be answered. If you still consider this open, please let me know.
