### ISSUE TITLE
Settings API: changing public_profile is not working

### ISSUE THREAD

**Issue by Davidmgc** [gpodder/mygpo#224]
I sent the following Curl:

> curl -X POST "https://gpodder.net/api/2/settings/Davidmgc/account.json" -H "accept: application/json" -H "Authorization: Basic UrowR87Fklr8FrnnrNo" -H "Content-Type: application/json" -d "{\"set\":{\"public_profile\":false},\"remove\":[]}"

My profile should be set to private now, but it isn't. Generally: One cannot set the public_profile setting in either way, true or false.

**Comment by bencomp** [comment]
The [documentation of the Settings API](https://gpoddernet.readthedocs.io/en/latest/api/reference/settings.html) mentions that you currently cannot set the account privacy via the API:

> `public_profile`: when set to False, sets all podcasts to private (as on <http://gpodder.net/account/privacy>, currently deactivated via API)

**Comment by SiqingYu** [comment]
Currently, the user profile page is shared with a token owned by the user who shares the page. If someone accesses the page without a token, he would be denied access. The `public_profile` hasn't been used in the backend yet.
<img width="504" alt="2020-02-01_19-21" src="https://user-images.githubusercontent.com/22290018/73591334-52e57800-4528-11ea-8947-bc1b70c71017.png">
