### ISSUE TITLE
Recognize CC licenses with https URLs

### ISSUE THREAD

**Issue by stefankoegl** [gpodder/mygpo#232]
https://gpodder.net/directory/+license contains a list of licenses. When selecting a license the podcasts that use this particular license are shown.

In 
https://github.com/gpodder/mygpo/blob/1950aae95d79c87bf703ec7f457fd84c2c9613f4/mygpo/web/utils.py#L204
the license URLs are matched against known patterns to show "nice" names instead of URLs. For creative commons licenses, only http URLs are recognized. http and https URLs should be recognized as identical.

**Comment by webpigeon** [comment]
I've written tests for this, I can't run them yet because i'm still importing the data :)

**Comment by stefankoegl** [comment]
@webpigeon, what’s your status on this? Any progress?

**Comment by webpigeon** [comment]
I wrote the code but had trouble getting a text environment set up :)

**Comment by stefankoegl** [comment]
Can you submit a pull request?

**Comment by stefankoegl** [comment]
I've created a pull request from your fork, see #279.
