### ISSUE TITLE
Upgrade Django to 2.2

### ISSUE THREAD

**Issue by stefankoegl** [gpodder/mygpo#234]
Currently Django versions are pinned to 2.1.7, which is not current anymore.

https://github.com/gpodder/mygpo/blob/81e3d13e00e6c3d6db7ee6a22734041bf6fde128/requirements.txt#L1

To keep dependencies up to date, Django should be updated to 2.2. Based on the [release notes](https://docs.djangoproject.com/en/dev/releases/2.2/) there should not be any major issues with the upgrade.

**Comment by MrPiethon** [comment]
How's the upgrade going? Need help?
