### ISSUE TITLE
gpodder.net account registration e-mail not received

### ISSUE THREAD

**Issue by RoyTheNewbie** [gpodder/mygpo#253]
I have the gpodder app on my Lenovo Thinkpad, running Ubuntu 16.04. I can download the podcasts I want. However, when I tried to register with gpodder.net, using a username and e-mail address, what should then happen is that I should receive an e-mail to confirm my application. _That e-mail does not arrive_. When I try to do it again I am still unsuccessful.
_What can be going wrong?_

**Comment by RoyTheNewbie** [comment]
@elelay Where was this issue transferred to?

**Comment by elelay** [comment]
@RoyTheNewbie gpodder/mygpo is the gpodder.net repository (contrary to gpodder/gpodder, which is for the desktop application).
Your question has a better chance to be answered there :-)

**Comment by RoyTheNewbie** [comment]
@elWhere was this issue transferred to?

> @RoyTheNewbie gpodder/mygpo is the gpodder.net repository (contrary to gpodder/gpodder, which is for the desktop application).
> Your question has a better chance to be answered there :-)

Many thanks for your help and for that information !

**Comment by RoyTheNewbie** [comment]
@elWhere was this issue transferred to?

> @RoyTheNewbie gpodder/mygpo is the gpodder.net repository (contrary to gpodder/gpodder, which is for the desktop application).
> Your question has a better chance to be answered there :-)

Many thanks for your help and for that information !

After repeated attempts to register, and not receiving an activation e-mail, I tried again today and was successful. If anyone helped behind the scenes to make this happen, thank you!

**Comment by FiSHYsolutions** [comment]
Registered an account, didn't received an activation-mail (in two different environments). Issue shouldn't be closed...
