### ISSUE TITLE
Developer docs insufficient to run test suite

### ISSUE THREAD

**Issue by nwallace** [gpodder/mygpo#255]
Tried to get a dev environment up and running to help out with #233. I followed the [installation instructions](https://gpoddernet.readthedocs.io/en/latest/dev/installation.html) and the [Postgres setup](https://gpoddernet.readthedocs.io/en/latest/dev/postgres-setup.html). I could run the development server fine, but when I ran `make test`, it failed for a couple of different reasons. The development instructions should include all steps necessary to run the tests as well.

The steps that are missing:

- Create the `envs/tests` directory with appropriate values
- Create the `envs/tests/MEDIA_ROOT` file with a value
- Create the `envs/dev` directory with appropriate values

I got the tests passing by `cp -r envs/local envs/test`, then updating the `envs/test/DATABASE_URL` appropriately, then `mkdir -p media/test && echo media/test > envs/test/MEDIA_ROOT`, then `ln -s local envs/dev`. At this point, the tests ran and passed.

I don't know if those steps are correct. I don't know what MEDIA_ROOT is supposed to be -- it's not documented on the [configuration page](https://gpoddernet.readthedocs.io/en/latest/dev/configuration.html). I also don't know what the difference is between `envs/dev` and `envs/local`. Are they just different naming choices for your development environment? If so, the `makefile` is inconsistent, because `dev-config` uses "local" while `test` used "dev".

Forgive my noobness -- I don't know Python or Django, so maybe that's some of my problem :slightly_smiling_face:

And, as always, thank you for gpodder! Hoping to contribute to help it stay in operation 😃

**Comment by stefankoegl** [comment]
Thanks for your report! You're absolutely right that the instructions are confusing. I have now simplified them so that only ``envs/dev`` is used. Can you please have a look at #256 and let me know if that answers your questions?
