### ISSUE TITLE
Environment setup automation

### ISSUE THREAD

**Issue by SiqingYu** [gpodder/mygpo#262]
I find the process of setting up the development environment is time-consuming.

I think Vagrant and Ansible can provision a VM quickly, and the environment can be consistent across developers.

I'll work on this issue.

**Comment by stefankoegl** [comment]
Sounds like a great idea!

**Comment by JeanFred** [comment]
In case this is helpful, I had started a docker-compose setup ages ago. The work in progress is still at https://github.com/JeanFred/mygpo/commits/docker If there is interest I can try getting back to it :)

**Comment by SiqingYu** [comment]
Thanks, @JeanFred :smile: 
This initiative is to onboard new developers with a quick development environment setup.
It's not as complicated as Docker Compose, which aims at the production environment. I can deal with this.

**Comment by JeanFred** [comment]
> In case this is helpful, I had started a docker-compose setup ages ago. The work in progress is still at https://github.com/JeanFred/mygpo/commits/docker If there is interest I can try getting back to it :)

Aaah, I had completely forgotten about it, but Stefan had continued work on this (with some bits from my fork) at #32.

@SiqingYu
> This initiative is to onboard new developers with a quick development environment setup.
> It's not as complicated as Docker Compose, which aims at the production environment. I can deal with this.

Up to you of course, but to clarify, docker-compose is not necessarily intended for prod − [using it for development is a common pattern](https://docs.docker.com/compose/#development-environments). In the case of mygpo, given that there are dependencies on fairly heavy services like Postgres and ElasticSearch, I’d expect using Docker to be faster to use than an Ansible provisioning. Anyhow, up to you! :-)

**Comment by lunamystry** [comment]
Yes please for an easier dev environment setup, I still can't get the tests to pass on a freshly cloned repo :-( 

I vote for docker/docker-compose though cause I worry about running a VM on this poor laptop of mine.

**Comment by outdooracorn** [comment]
I was just thinking about trying to get something like this setup. I also vote for Docker instead of a VM.

Ansible also has [good docker support](https://docs.ansible.com/ansible/latest/scenario_guides/guide_docker.html) and would be more flexible than docker-compose if you wanted to go that route instead.

**Comment by SiqingYu** [comment]
OK, as most of you prefer Docker, I'd like Docker to provision then.

**Comment by SiqingYu** [comment]
Move to https://github.com/gpodder/mygpo/issues/355
