### ISSUE TITLE
Merging Transifex projects

### ISSUE THREAD

**Issue by yarons** [gpodder/mygpo#297]
I opened a Transifex project because I couldn't find your project, I already have some languages fully translated and I can't request access to your project.

My project address is https://www.transifex.com/yaron/gpodder/dashboard/

I'm willing to give full access and move the translators over to your project.

Sorry for the mess, thanks!

**Comment by stefankoegl** [comment]
Could you please give access to my user stefankoegl? I'll have a look then. 

Thanks!

**Comment by yarons** [comment]
Done, feel free to consult me, I have you fill permissions, make sure you don't remove anything.

Thank you and good luck!

**Comment by stefankoegl** [comment]
Steps to merge translations from the two transifex projects.

1) Temporarily point `.tx/config` to @yarons' project.

````diff
$ git diff .tx/config
diff --git a/.tx/config b/.tx/config
index 2860a978..b903a65f 100644
--- a/.tx/config
+++ b/.tx/config
@@ -1,7 +1,7 @@
 [main]
 host = https://transifex.com
 
-[gpoddernet.gpoddernet]
+[gpodder.website]
 file_filter = mygpo/locale/<lang>/LC_MESSAGES/django.po
 source_file = mygpo/locale/en/LC_MESSAGES/django.po
 source_lang = en
````

2) Pull translations 

````
$ tx pull -a -f
````

This pulls new and updated translations

````bash
$ git status -s
 M .tx/config
 M mygpo/locale/fr/LC_MESSAGES/django.po
 M mygpo/locale/he/LC_MESSAGES/django.po
?? mygpo/locale/br/
?? mygpo/locale/nl_NL/
````

3) Revert temporary changes to .tx/config

````
$ git checkout .tx/config
````

4) Commit new translations

````bash
$ git add mygpo/locale/
$ git commit
$ git push
````

This created 2b04bc7ea0b2950165a63922f64ef154a28e190b.

5) Update PO files

````
$ make update-po
$ git add mygpo/locale
$ git commit
````

This created 14e6116bc954ff59926b99a99d0062ac66350df8

6) Push to Transifex

````
$ tx push -s  # source files
$ tx push -t  # translations
````

7) Push to GitHub

````
$ git push
````

**Comment by stefankoegl** [comment]
@yarons can you please double-check and delete your Transifex project if everything is OK?

**Comment by yarons** [comment]
Succesfully removed!

Please add my Transifex user Yaron as a Hebrew coordinator, thank you :) (Currently I'm part of the Dutch team, it may take several years for me to start and contribute in this language judging by my German skills).

I told the other translators to contact you in case they want to continue to contribute to your project.

Thank you so much!

**Comment by stefankoegl** [comment]
Done.
