### ISSUE TITLE
GitHub Projects boards

### ISSUE THREAD

**Issue by SiqingYu** [gpodder/mygpo#331]
I suggest open new project boards on https://github.com/gpodder/mygpo/projects so contributors can track the progress. It can also helps assign the issues to contributors.

Tasks from below can be added to the project boards:
Ensure development knowledge transfer · Issue · stefankoegl/mygpo-internal
https://github.com/stefankoegl/mygpo-internal/issues/15

**Comment by stefankoegl** [comment]
You should now have the permissions to set up project boards as required. Please give it a try and close the issue if it is working.

**Comment by SiqingYu** [comment]
I suggest that we keep two boards "Bug Triage" and "Features" for simplicity's sake. We can assign labels such as "api", "search" to issues so we can see what areas they belong to. @stefankoegl @fundatillus
