### ISSUE TITLE
subscribers_last_week API response wrong

### ISSUE THREAD

**Issue by ByteHamster** [gpodder/mygpo#375]
Hi,

The [gpodder API description](https://gpoddernet.readthedocs.io/en/latest/api/reference/directory.html) says:
> The `subscribers_last_week` field may be set to zero if no data is available. The client can use the `subscribers_last_week` counts to re-sort the list and get a ranking for the last week.

In https://gpodder.net/toplist/10.json though, the `subscribers_last_week` field is always the same as the total subscriber number. Looks like this got broken in commit 30530aa92c964c72f0203d179f8bf7d7ef38bc53. Below, you can see an excerpt from [mygpo/api/advanced/directory.py](https://github.com/gpodder/mygpo/blob/master/mygpo/api/advanced/directory.py) that shows that the `subscribers_last_week` field is filled with the total subscriber number.

```
subscribers = podcast.subscribers
last_subscribers = podcast.subscribers
```

**Comment by SiqingYu** [comment]
Thanks for your feedback. I will fix this as soon as possible.

**Comment by SiqingYu** [comment]
The `prev_subscriber_count()` method was removed from the `Podcast` model. The current podcast model doesn't have support for historical subscriber number tracking. I'll amend the API documentation.

**Comment by SiqingYu** [comment]
Anyway, I don't think the `subscriber_last_week` field has any use. I'll close this issue for now. Feel free to comment or open new an issue if you have any suggestion.

**Comment by ByteHamster** [comment]
> Anyway, I don't think the subscriber_last_week field has any use.

I think it could be useful to show trending podcasts. For example, the iTunes charts currently show many podcasts about the new Corona virus. Anyway, re-adding is additional work, so officially removing the field is probably the best option, for now :) I hope that removing does not break clients.

**Comment by SiqingYu** [comment]
@ByteHamster We will preserve the old APIs while migrating to the new API. Manually curating content requires a lot of human labor. Currently, we don't have many human resources to dispose of.

**Comment by ByteHamster** [comment]
> Manually curating content requires a lot of human labor.

subscriber_last_week allows to discover trends without manual curation.

**Comment by SiqingYu** [comment]
@ByteHamster Do you need this feature? If you do, I can put it in the backlog and add it in the future.

**Comment by ByteHamster** [comment]
AntennaPod displays a list of top podcasts on gpodder. That list never changes because the total number of subscriptions changes quite linearly. A subscribers_last_week could help to make the list more interesting. Anyway, the main podcast discovery toplist in AntennaPod is created from iTunes. They probably have better suggestions (wider audience, by country), even if gpodder had the subscribers_last_week field. I just wanted to try and see if gpodder shows similar trends to iTunes and discovered that they are broken. Because AntennaPod already has the iTunes trends, I do not actually need the toplist feature in gpodder. This was mainly just personal interest, not actual need. Spend your time on something else :)

**Comment by SiqingYu** [comment]
@ByteHamster Thanks for your elaboration. Currently, we don't have the user base as large as iTunes. The trends might not be practical in our case. It's just my two cents. :blush:
