### ISSUE TITLE
how to retrieve audio files of an old podcast at gpodder.net?

### ISSUE THREAD

**Issue by amulmago2020** [gpodder/mygpo#403]
hello friends: I found an old podcast from Business Week, Climbing the ladder" on gpodder.net. The First 100 Days - BusinessWeek -- Climbing the Ladder — gpodder.net 

https://gpodder.net/podcast/businessweek-climbing-the-ladder/the-first-100-days 

But I am not able to find the audio files of this. Can someone help?

**Comment by stefankoegl** [comment]
In the line below the episode title there is a small downloadet  symbol, which opens the original media file which is hosted by the podcast publisher. 

In this particular case, the media file is no longer available. gpodder.net itself does not store any media files.
