### ISSUE TITLE
unable to log into gpodder.net with error 500

### ISSUE THREAD

**Issue by bobreidx** [gpodder/mygpo#414]
gpodder integration with AntennaPod for Android had been going smoothly until a couple of days ago when it started throwing errors and claiming that login/pwd were incorrect. When attempting to log into the web portal in Chrome, I get a 500 error. I use BitWarden for pwd's.

**Comment by pcanning** [comment]
I've been seeing the same behavior (AntennaPod for Android unable to connect) for several days and "500 - Internal server error. I didn't try logging in to the web site (https://gpodder.net/login/ using firefox) until yesterday, but I'm also seeing that fail with the message "The service is currently overloaded. Please try again later or contact us.".

**Comment by awalo666** [comment]
I have the same issue with AntennaPod and firefox

**Comment by winny-** [comment]
Me too. Instead of commenting with more "me too" comments, please thumbs up this comment.

**Comment by stefankoegl** [comment]
There was a database issue, which should now be fixed. Logins should be working again.

cc @fundatillus

**Comment by alexanderadam** [comment]
It's happening right now again.
![500 - Internal server error. The service is currently overloaded. Please try again later or contact us.](https://user-images.githubusercontent.com/372620/98230310-4c72a980-1f5b-11eb-895e-868e0ccc3b49.png)

**Comment by devinprater** [comment]
It's happening now again.

**Comment by e-t-l** [comment]
It's now 2022 and I'm still seeing this. Is there any fix for it?

**Comment by CoolerWuffi** [comment]
Yea I wanted to register myself but it seams to be overloaded again
