### ISSUE TITLE
Error initialising mygpo

### ISSUE THREAD

**Issue by adamvoss** [gpodder/mygpo#44]
_From @TalmarGrosskotz on March 2, 2017 14:4_

Step by step I progress on running mygpo on my Raspberry Pi, but now I have run into a new error I can' t make sense of. It happens after running `python manage.py migrate`:

Traceback (most recent call last):
 File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in         
     execute_from_command_line utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/mygpo/mygpo/api/__init__.py", line 27, in <module>
    from mygpo.utils import parse_request_body
  File "/root/mygpo/mygpo/utils.py", line 236
   print('\r', end=' ', file=stream)
                        ^
SyntaxError: invalid syntax

Can anybody help me?

_Copied from original issue: gpodder/gpodder#236_

**Comment by adamvoss** [comment]
What is your python version?  (`python --version`)

@thp, should the issue tracker perhaps be enabled on [gpodder/mygpo](https://github.com/gpodder/mygpo)?

**Comment by adamvoss** [comment]
@TalmarGrosskotz I don't know the right way to fix this for that code-base generally, but the issue is that it is using the [print function](https://docs.python.org/2/library/functions.html#print) (a la Python 3) rather than the print statement from Python 2.

Try adding,

    from __future__ import print_function

in the imports of utils.py to bring the print function into scope.

**Comment by adamvoss** [comment]
_From @TalmarGrosskotz on March 2, 2017 14:27_

I am using python 2.7.12


Am 02.03.2017 um 15:11 schrieb Adam Voss:

**Comment by adamvoss** [comment]
_From @TalmarGrosskotz on March 2, 2017 18:55_

That worked, thx.

⁣Gesendet mit BlueMail ​

**Comment by adamvoss** [comment]
_From @TalmarGrosskotz on March 2, 2017 20:55_

I am getting closer. It seems that I have to manually install everyting (every single package) under python 2.7 to get things running. `pip install -r requirements.txt` seems to do all under python3 while `pip2 install -r requirements.txt` fails to work.

**Comment by adamvoss** [comment]
_From @TalmarGrosskotz on March 2, 2017 21:1_

I am so close to giving up :(
Still trying to successfully run `python manage.py migrate`.
After working out several problems with `urllib` and so on i get the following error:
`FATAL:  password authentication failed for user "mygpo"`

I have absolutely no idea how and where to fix it.

**Comment by adamvoss** [comment]
@TalmarGrosskotz What is the status of this?  Your last message seems to indicate you had a simple authentication error (bad password, wrong user name, etc).  Did you have a stacktrace for the error?

**Comment by adamvoss** [comment]
_From @TalmarGrosskotz on April 12, 2017 6:0_

Sorry for not getting back here. I kinda lost patience over it. I think the Problem has to do with Python 2/3 confusion. Some libraries seem to have changed in Python 3 and others things don't work when I try using 2.7 (as far as I remember it had something to do with urllib).
I will the again sometime but right now I don't have the time. If anybody figures it out I'be happy to know.



Gesendet mit BlueMail

**Comment by stefankoegl** [comment]
I've updated the installation documentation which is now published at http://gpoddernet.readthedocs.io/en/latest/dev/installation.html. If you follow those instructions, you should be able to get mygpo running. If it does not work for you, please report at which step you are stuck exactly.
