### ISSUE TITLE
some podcasts not updated in gpodder.net web ui

### ISSUE THREAD

**Issue by adamvoss** [gpodder/mygpo#47]
_From @elelay on April 1, 2017 13:58_

For instance https://gpodder.net/podcast/si-tu-ecoutes-jannule-tout shows latest from jan. 15, 2016 even if the feed has entries as fresh as Yesterday.

_Copied from original issue: gpodder/gpodder#260_

**Comment by adamvoss** [comment]
_From @ldexterldesign on June 9, 2017 10:31_

+1

**Comment by adamvoss** [comment]
@elelay I think you have done some work with mygpo, know if a local install of mygpo is affected by this?  See https://github.com/gpodder/gpodder/issues/314#issuecomment-307839308

/cc @ldexterldesign

**Comment by adamvoss** [comment]
_From @elelay on June 12, 2017 21:21_

I was able to install my own instance of mygpo.
Unfortunately, I wasn't interested in the web ui at the time, and didn't setup feed refreshes, so I can't help you in configuring that.

**Comment by stefankoegl** [comment]
Podcast updates have been running more frequently recently. Please let me know if the problem persists.
