### ISSUE TITLE
Stuck in activation loop

### ISSUE THREAD

**Issue by adamvoss** [gpodder/mygpo#48]
_From @procyon12lotor on May 22, 2017 21:3_

Deleted my account to quickly reset settings, and now:

-Cannot re-register account because username and email address are already taken.
-Cannot log into account on any synced devices.
-Cannot log into website, because my account needs activation which results in the following email.

> Click on the link below to activate your account on gpodder.net
> 
> https://gpodder.net/activate/None

-Cannot activate account because the link in the email "https://gpodder.net/activate/None" doesn't work.

Would be nice to have some way of releasing my account. I don't really want to have an entire email address only for this account.

Is there a way to free the email address associated with a deleted account?

_Copied from original issue: gpodder/gpodder#303_

**Comment by adamvoss** [comment]
Pinging @stefankoegl since I have gathered from context that he is the maintainer of gpodder.net/mygpo.

**Comment by adamvoss** [comment]
_From @procyon12lotor on May 26, 2017 18:31_

Thanks vossad01. @stefankoegl
Update: I just tried to activate again, and I receive the same email with the broken link to activate, so there is not a 24-48 hour cooldown for re-registration.

**Comment by procyon12lotor** [comment]
@adamvoss Anyway you can just delete this post or obscure my login in the original post?

**Comment by adamvoss** [comment]
@procyon12lotor I believe I have addressed your most recent request.  Please let me know if I have misunderstood.  Thanks!

**Comment by procyon12lotor** [comment]
@adamvoss This should probably be closed. The gpodder people just don't offer account support requiring intervention on their end. Emails cannot be reused.

**Comment by procyon12lotor** [comment]
@stefankoegl I appreciate it, but no longer necessary. Thanks! @adamvoss Can you please close this issue?

**Comment by procyon12lotor** [comment]
@adamvoss Is it possible to delete any mentions of my @username in these posts? I am trying to stop my username from being indexed by search engines, and if I change my username, your mentions will still remain. Thanks.
