### ISSUE TITLE
Update documentation links

### ISSUE THREAD

**Issue by adamvoss** [gpodder/mygpo#52]
There are links to http://wiki.gpodder.org/ throughout the website.  However, this content has moved (per https://github.com/gpodder/gpodder.github.io/issues/9#issuecomment-316443858).  It would be great if gpodder.net updated its links so users did not need to go from gpodder.net -> wiki.gpodder -> readthedocs, and instead could go from gpodder.net -> readthedocs.

**Comment by hovancik** [comment]
I could help with this. Help wanted?

**Comment by stefankoegl** [comment]
Sure, help is always wanted! Please ping me if you have any questions or if you have a pull request to review.
