### ISSUE TITLE
502 Error - is gpodder.net down? 

### ISSUE THREAD

**Issue by chegeiser** [gpodder/mygpo#527]
I'm not sure if this is the right place, but I just tried to go to the gpodder.net site and got a 502 error. Is the site down? I was able to access the site with the wayback machine, but was not able to register - at least the confirmation email hasn't been received after about a 30 minute wait.

**Comment by RKDTOO** [comment]
Ditto.

**Comment by smammy** [comment]
Before this gets out of hand: _please,_ folks, don't add "+1"/"ditto" comments on this issue. You can react 👍 to the original comment and/or subscribe to the issue instead. Thanks!

**Comment by smammy** [comment]
On the gpodder mailing list, maintainer @fundatillus says:

>  The service isn’t “down” exactly. If you refresh it a bunch, you eventually get in. We’ve had performance issues for a while and I think I need to do some NGINX configuration work… will keep everyone posted.

Ref: [[gpodder] Re: gpodder.net down](https://www.freelists.org/post/gpodder/gpoddernet-down,1)

**Comment by mtedaldi** [comment]
I'm not sure if it is the same problem or related. At the moment, gpodder.net seems to work quite well except if I want to login. than I get an Error 500.
`500 - Internal server error.
The service is currently overloaded. Please try again later or contact us.`

I've tried it over several days, always the same result.

**Comment by alexis26** [comment]
> 
> 
> On the gpodder mailing list, maintainer @fundatillus wrote on 30 November (today) to say:
> 
> > The service isn’t “down” exactly. If you refresh it a bunch, you eventually get in. We’ve had performance issues for a while and I think I need to do some NGINX configuration work… will keep everyone posted.
> 
yes, actually I had no more connection problems...
However none of my subscriptions have been synchronized since the beginning of the report...

for me, the state of the synchronization service is always down
(not for you?)

**Comment by mcepl** [comment]
https://downforeveryoneorjustme.com/gpodder.net

Seems quite dead. Neither AntennaPod nor https://gpodder.net get anything other than 502 Error (even after multiple attempts).

**Comment by vanguard737** [comment]
Just for fun, I pointed an [UptimeRobot](https://uptimerobot.com/) monitor at https://gpodder.net.  It's been running for a little over 24 hours now.  In that period, https://gpodder.net shows **~15% uptime**.  Looks like a few hits get through, and most don't.

I've attached the graphical output from UptimeRobot, as well as a CSV with some additional details about the up-vs.-down time periods.  Perhaps the timing info will point the team to some informative logging on the back end...

[uptimerobot-gpodder-logs.csv.txt](https://github.com/gpodder/mygpo/files/5749372/uptimerobot-gpodder-logs.csv.txt)


![gpodder_uptimerobot_20201228](https://user-images.githubusercontent.com/2373477/103254269-404b0d00-494a-11eb-98a1-6b7f9c753688.PNG)

**Comment by fundatillus** [comment]
Yes, the site is down right now. I’m working on some upgrades and am having trouble getting things to work again. I’m trying to avoid wiping and starting from scratch, but that may be necessary if I can’t get it working in a couple days.

**Comment by frittentheke** [comment]
> Yes, the site is down right now. I’m working on some upgrades and am having trouble getting things to work again. I’m trying to avoid wiping and starting from scratch, but that may be necessary if I can’t get it working in a couple days.
> […](#)
> On Dec 26, 2020, at 4:39 PM, Matěj Cepl ***@***.***> wrote: https://downforeveryoneorjustme.com/gpodder.net Seems quite dead. Neither AntennaPod nor https://gpodder.net get anything other than 502 Error (even after multiple attempts). — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.


@fundatillus thank you very much for looking into things! By any chance, is there anything your could need any help with? 
Is this rather a hardware or data-consistency issue or more of a scalability issue with the current system / setup?

**Comment by jehb** [comment]
Just checking in. I'm still having regular sync errors reporting 502 from both desktop and mobile clients. Is there anything that we can do to help from the admin side? I'd be happy to lend a hand helping debug the configuration, or throw a few bucks towards a beefier host, depending on what's holding fixing the issue back.

**Comment by tgp1994** [comment]
My understanding from the Slack channel is that they're in the troubleshooting stage and trying to nail down the root issue. I think they'd appreciate any help!

**Comment by barkengmad** [comment]
I really appreciate this sync service. I wish I had the technical skills to help. Best of luck.

**Comment by frittentheke** [comment]
> My understanding from the Slack channel is that they're in the troubleshooting stage and trying to nail down the root issue. I think they'd appreciate any help!

If help is still wanted, do you mind pointing me to that  Slack channel or maybe get an invite if required ?

**Comment by tgp1994** [comment]
I think someone just commented looking for the slack channel, here it is if you'd like to join: https://join.slack.com/t/gpodder-net/shared_invite/zt-aaiagl5i-uZeqVR8w1Yf_G~9rhktRfw

**Comment by alexis26** [comment]
Hi,
it seem to work ... ?!?

**Comment by mcepl** [comment]
Yes, seems to work. Could this ticket be closed?

**Comment by alexis26** [comment]
Maibe not for now ...
I spoke too quickly...they have to work on it
i just having the "500 - Internal server error."

**Comment by sevrinsky** [comment]
I haven't been able to login to gpodder.net at all for the last few days. Is anyone working on this?

**Comment by mcepl** [comment]
I think this ticket should be closed. gpodder.net has been responsive for some time.

**Comment by Eiion** [comment]
Apparently this still is an issue.

**Comment by bouktin** [comment]
Hi @Eiion, can you clarify what error you get and on which page(s)? 
Are you logged in? Since when are you experiencing this error?

Note : if you are experiencing this issue only when trying to register, then this is a known issue and being investigated in https://github.com/gpodder/mygpo/issues/647 . In this case, kindly update that ticket instead.

Thank you
Thomas

**Comment by Eiion** [comment]
Hi @bouktin, it indeed is an issue that occurs when trying to register.
Thanks, I'll comment there.
