### ISSUE TITLE
Unable to login using clients (gPodder linux, AntennaPod)

### ISSUE THREAD

**Issue by paulvdbles** [gpodder/mygpo#561]
I set up my own server to host the gpodder webservice.
I can login using the browser, however when I try to login using a client (gPodder desktop app, AntennaPod) it says my credentials are wrong.
![2021-02-26T09-06-52Z](https://user-images.githubusercontent.com/17083597/109273616-b8329800-7812-11eb-8f8a-8d49523d9d1d.png)
![WhatsApp Image 2021-02-26 at 09 14 53](https://user-images.githubusercontent.com/17083597/109273997-3bec8480-7813-11eb-8367-6abd90cdac5d.jpeg)

**Comment by rw-django-fan-2020** [comment]
Setting up my own gpodder server locally does work for me. I am able to connect und synchronise AntennaPod. Maybe you have to add the prefix "http://" or "https:// and a port number as suffix.

**Comment by fundatillus** [comment]
I don't think this is an issue with mygpo. The code used to run the production site comes straight from this repo. 

Take a look at how to configure the app to accept connections from other hosts. You will likely have to look into how to deploy Django in production. Check out this resource from the Django project: https://docs.djangoproject.com/en/3.2/howto/deployment/
