### ISSUE TITLE
Website Error 500 but only on log-in attempt.

### ISSUE THREAD

**Issue by andysavage** [gpodder/mygpo#568]
Hi the website appears to be working fine, except when I try to log in, then it gives an error:

> 500 - Internal server error.
> The service is currently overloaded. Please try again later or contact us.

Is this something you are already aware of or is it new? Been like this at least a few days now.

**Comment by MarkWieczorek** [comment]
I am encountering the same problem, but it turns out that it is only not working with Firefox. I tried logging in using Brave and it worked fine. I experimented with disabling extensions in Firefox, but that didn't seem to help.

**Comment by andysavage** [comment]
> I am encountering the same problem, but it turns out that it is only not working with Firefox. I tried logging in using Brave and it worked fine. I experimented with disabling extensions in Firefox, but that didn't seem to help.

Well, at least I'm not the only one... I am using Chrome.

**Comment by lptex** [comment]
Getting this error today, can't log in and get anything set up. Get 500 error on Brave Browser with shields up, and with shields down. Also get the error on Edge Browser. This was on my desktop.

Tried to login in from my android phone, using Brave Browser for Android, got logged in. This is weird.

**Comment by ryoung29** [comment]
This should be resolved now.
