### ISSUE TITLE
500 - Internal server error when loggin in

### ISSUE THREAD

**Issue by madushan1000** [gpodder/mygpo#573]
When I try to login at https://gpodder.net/login/ I get a 500 error. I tried to set up my own instance and consume just your api, but seems like the UI is not really meant to be used that way(no way to disable sign ups etc..)

**Comment by kolorafa** [comment]
Same here, the api is working, sucessfully getting logged-in with apps, but getting 500 error on gpodder.net/login.
:(

**Comment by oXvTV** [comment]
Same here.

**Comment by fundatillus** [comment]
Is this still a problem? It's blazing fast for me right now...

**Comment by oXvTV** [comment]
Yes I still get 500 - Internal server error. Strange.

**Comment by fundatillus** [comment]
As I'm working in the system, I'm getting 500s for certain functions in the admin panel, but the site is speedy and I have no trouble logging in. 

We'll keep working it.

**Comment by prosario2000** [comment]
At least the problem for me has been solved. However, I did something yesterday that may be a key to the problem, but I'm not sure. When I first tried to login to Podder.net, it was through Brave, a Chromium derivative, where it already has info on my Google accounts I use to log in.  I tried to login through Firefox, where it does not have Google info. I succeeded in login.  However, when I logged out, and tried to login using my Google account in Firefox, then I got the 500 - Internal Server Error.

**Comment by zunicero** [comment]
I've created an account a few weeks ago and didn't manage to login a single time since then. Syncing AntennaPod and the desktop application works without a problem though.

**Comment by oXvTV** [comment]
Can I ask how you are able to sync AntennaPod with gPodder desktop app without being able to login?

**Comment by zunicero** [comment]
I didn't make myself very clear, sorry. I wasn't able to login using the website. However it works fine using the apps.

**Comment by oXvTV** [comment]
Ok. Do you mean you are able to sync AntennaPod to the desktop gPodder app without logging in or?

**Comment by zunicero** [comment]
Login and sync works in AntennaPod and gPodder. It just doesn't work using the web browser.

**Comment by oXvTV** [comment]
Ah, excellent! Thanks, hadn't considered that - works for me too.

**Comment by ryoung29** [comment]
related to https://github.com/gpodder/mygpo/issues/574. Working on it now.
