### ISSUE TITLE
Can't activate account

### ISSUE THREAD

**Issue by ViRUS2012** [gpodder/mygpo#593]
Hi!

I've just registered on gpodder.net, but the e-mail that arrives in my inbox to activate my account points me to 
https://gpodder.net/activate/None and therefore I can't activate my account.

Help?

**Comment by ViRUS2012** [comment]
LOL, I registered using another e-mail account and now I received what seems to be a valid activation e-mail, but when I clicked on the link I got an Error 400 page, and if I try to log in with the new account I just created, I get an Error 500.

Is this service still functioning or has it been abandoned?

**Comment by ryoung29** [comment]
Working on this now. Duplicate
