### ISSUE TITLE
[Request] Potential part time contributor

### ISSUE THREAD

**Issue by Ryochan7** [gpodder/mygpo#630]
As mentioned in #228, I am available to dedicate some time to this project. This project definitely needs the help and I could contribute some fixes to this project. Can you please look into giving me some form of permission to contribute directly to this repo?

**Comment by fundatillus** [comment]
@Ryochan7 please join us the Slack channel: https://gpodder-net.slack.com/archives/CB5QBHTA8

@stefankoegl please grant @Ryochan7 the proper permissions in the repos.

**Comment by Ryochan7** [comment]
okay. I have joined the Slack channel.

**Comment by fundatillus** [comment]
Thank you for the awesome contributions you're making @Ryochan7.
