### ISSUE TITLE
GitHub Action to check build on PR not working

### ISSUE THREAD

**Issue by clementsjosh** [gpodder/mygpo#635]
I'm currently checking builds using my fork and personal Travis CI account. This is a single point-of-failure, so I've tried to setup a GitHub action which is triggered properly, but the database is not accessible, so the build always fails. 

Anyone that can help with this?

**Comment by Ryochan7** [comment]
Finally got the workflow working on my fork. Needed to change PostgreSQL vars a bit and needed to downgrade the coverage module to version 5.5; coveralls does not like coverage 6.0.x and will error out.

https://github.com/Ryochan7/mygpo/tree/actions_test

**Comment by Ryochan7** [comment]
I'll make a new branch with just the final changes in a bit. Don't really need all the test commits involved.
