### ISSUE TITLE
License of gpodder.net logo

### ISSUE THREAD

**Issue by mogwa1** [gpodder/mygpo#640]
Just a quick question: I'm working on integration of gpodder.net syncing in Kasts (https://invent.kde.org/plasma-mobile/kasts) and I would like to use the gpodder.net logo.  However, I can't find a license for the logo anywhere, so I'm not sure if it can be used freely or not.

**Comment by auouymous** [comment]
@thp should know.

**Comment by thp** [comment]
I created the icon, and it can be used in applications to refer to the gpodder.net service.

**Comment by mogwa1** [comment]
Thank you, I'll add a copyright statement on your name.

Just to be sure: what's the license that I should attribute to the logo: CC-BY-SA-4.0 or CC0-1.0 or GPLv2 or ...?  I'm trying to be fully reuse compliant. :)
