### ISSUE TITLE
activation email not being sent

### ISSUE THREAD

**Issue by gdos** [gpodder/mygpo#66]
I still not have not received my activation email (nor a password reset email) to get my account going. yes, I checked my spam folder and yes, have waited several days.

**Comment by cweiske** [comment]
I created an account today and got an activation mail sent.

**Comment by viamyeye** [comment]
I'm having the same problem. I haven't received the activation email or when attempting to login before activation I receive: 

> Please activate your account first. We have just re-sent your activation email

**Comment by stefankoegl** [comment]
Sorry for the late response. For those still having problems, can you please either post your username / email address here, or send it to stefan@skoegl.net?

**Comment by stefankoegl** [comment]
@viamyeye I've just activated your user. I tried to reply to your email, but my mail could not be delivered (I don't want to disclose any error message or further details here publicly).

**Comment by jurgenhaas** [comment]
I'm having the same issue. @stefankoegl I've just send you an email.

**Comment by jurgenhaas** [comment]
Tried it again today and this time the email came in.

**Comment by SadMonk** [comment]
The same problem just popped up for me as well.

**Comment by SadMonk** [comment]
This issue just popped up for me as well. How long is the usual delay between registration and receiving the mail?

On another note, I'm not sure if keeping a newly registered user locked out of his account as long as he doesn't get that activation mail is a good thing as it just completely stops any interaction with the site for the time being and thus might lead to quite some frustration.

**Comment by hansluk** [comment]
I am having trouble sign-ing up.

Is there something we could help with the server on the activation step?

**Comment by suuuz** [comment]
I am not able to sign up either. I get a '502 Bad Gateway' error when I try it Firefox. 

When I try with internet explorer I get the following message "Attention, Attention!
It seems that https://gpodder.net/registration/resend has linked to gpodder.net to get you to change some data. This will possibly change some of your data / settings!. Do you really want to continue? If in doubt, chose No." (nothing seems to happen when I click 'yes'.

**Comment by stefankoegl** [comment]
I have fixed the underlying issue and resent all email that have been reported. If any are still missing, please let me know here. Thanks!
