### ISSUE TITLE
Cant create new account with the same email, after the old account is deleted.

### ISSUE THREAD

**Issue by anyuzu99** [gpodder/mygpo#672]
email: sayomelu@outlook.com

**Comment by sayomelu** [comment]
the email sent to me is:

Click on the link below to activate your account on gpodder.net

https://www.gpodder.net/activate/None

**Comment by moong8te** [comment]
Hello Sayomelu,

I wanted to generally create a new account but it seems that registrations have been disabled in general for months now.

I can only assume that the same it true for what you are trying which to the system looks like a new registration - I suppose.

**Comment by fundatillus** [comment]
@anyuzu99, please email me at josh@fndtls.co if you're still having trouble.
