### ISSUE TITLE
When do you re-open your webservice for new registrations? 

### ISSUE THREAD

**Issue by moong8te** [gpodder/mygpo#673]
Hello gpodder Team,

I am currently in the process of switching to AntennaPOD to have a client that supports Podcast and progress syncing across devices.

AntennaPOD is suggesting to use gpodder for this.
Unfortunately you are currently not accepting new registrations for your service for new users for more than a month.

Can you estimate when you have extended your capacities to be able to allow new users?
Do you have a current donation campain running that needs to be fullfilled to support this expansion that users can contribute to?

Best Moongate

**Comment by moong8te** [comment]
I this project still current and actively supported by its creators?

**Comment by Ryochan7** [comment]
Not really. As it is, gpodder.net is pretty much useless and it seems nobody wants to make it functional.

**Comment by moong8te** [comment]
I see. 

I could see that other services like spotify or pocket casts have adopted the idea of Podcast syncing in their apps over time.
They are charging for it and I guess there are users that like this "full service" convenience and don't mind being locked in.

I personally rather like the idea to have flexibility and choice.
I find it generally very generous for projects to provide free or donation based service like in this case.
That said the donation link is also broken.
Maybe the service just generated more costs and issues over time than satisfaction for the creators.

I tried to reach out to Stefan which I understand is the original creator of gpodder.net and potentially the sync service.
But so far no reply.

If I had a wish I would like to see a raspberry Pi version that could be installed as a local server.
But I have no idea how complex a port from its current status to a stable version would be.

I found others experimenting with GPodder Sync as a plug-in for nextcloud:
https://apps.nextcloud.com/apps/gpoddersync

I have nextcloud running on a dedicated raspberry Pi and will give it a try.
But installing nextcloud on raspi and getting it configured quite decent is not very sraight forward.

In any case I will post my results with gpodder and nextcloud after giving it a spin.
I will also report if i get a reply from Stefan.

**Comment by JumpLink** [comment]
I would also like to sync my podcasts with AntennaPod and would also like to create an account for this on gpodder.net. I thought maybe a donation would help, but [the PayPal link](https://gpodder.net/contribute/) no longer works.

**Comment by MaSchwarz** [comment]
I stumbled upon this project a few days ago. The idea of syncing your podcast subscriptions between different platforms and clients sounds quite appealing to me. But I couldn't give it a try yet, because the registration site just returns a status code 500.

This issue suggests that the project has been abandoned. I was wondering if there are any statements by the maintainers about this. 

Does anybody known an open source alternative?
(that doesn't require an entire nextcloud instance ;-))

**Comment by moong8te** [comment]
Hello JumpLink, MaSchwarz,

I started this thread because I has the same requirements for AntennaPod / gpodder and ran into the same issues.

- project owner not replying to private email
- donation link obsolete
- creation of new gpodder service account not possible
- no project status statement to be found
- no one from this project replying to this or other threads with a comment in weeks

My next step would have been to try and get in touch with the makers of AntennaPod asking them if they are aware that their only sync implementation seems to be broken and if they are planning to revamp this feature with their own creation.

Although I want to use open source for this I reactivated my free pocket casts account until such a solution becomes available in the future. I can now sync podcasts, my playlist and every progress up to the second across all my devices.
Just what I was hoping for when I tried to apply for a gpodder account two weeks ago.

If anybody knows of a working open sources cross device podcast sync solution or if this service ever becomes available again please grop me a line. Would be much appreciated.

**Comment by Ryochan7** [comment]
podgrab is one alternative that has been posted here before. I have never played with it myself.

https://github.com/akhilrex/podgrab

**Comment by MaSchwarz** [comment]
Thank you, I'll have a closer look at it in the next couple of days.

**Comment by JumpLink** [comment]
You can also define your own Server in AntennaPod, so I think you could also host your own gpodder instance for synchronisation

**Comment by moong8te** [comment]
> You can also define your own Server in AntennaPod, so I think you could also host your own gpodder instance for synchronisation

Hello Pascal, that would possibly be an option which I raised in my third post from the top.
>If I had a wish I would like to see a raspberry Pi version that could be installed as a local server.

Can you provide more insides how to implement your own gpodder instance for syncronization as you are suggesting.
Providing the implementation guide you seem to be referencing would be very helpful.

**Comment by JumpLink** [comment]
@moong8te Sorry,  have currently not the time for that :(

**Comment by gillib** [comment]
Maybe one of you guys knows how to help me. 
I have a podcast android app based on gpodder. I'm moving to a new device. Does anyone know how I can sync the "already listened" list with the new device?
Maybe which files I should copy over or any migration tool?

Thanks!

**Comment by fundatillus** [comment]
Resolved. #647
