### ISSUE TITLE
Feed works in Linux but not in Windows

### ISSUE THREAD

**Issue by LostPuppy24** [gpodder/mygpo#68]
Hello,  this URL "http://www.creationmoments.com/daily-rss" works on my Linux machine in gPodder.  When I try to run the same feed in Windows10 it gives me an error msg: Could not add some podcasts.
http://www.creationmoments.com/daily-rss: Got HTML document instead.

Is there a way to get this to work in Windows?

Linux version: 3.5.2 / Windows 10 version: 3.9.3

Thanks for the help.

LostPuppy24

**Comment by Questor321** [comment]
Hi! I have a similar problem in that 'Windows 10' will not download future episodes of a podcasts stating that there is a "certificate verification error". As this:
![error_capture](https://user-images.githubusercontent.com/29838421/31622400-4e1622dc-b26a-11e7-9d47-d92b8cf54e22.PNG)
I believe this a problem within Windows as it works fine under Linux Cinnamon Sarah. Any help while I try to find reasons for this?

**Comment by adamvoss** [comment]
@LostPuppy24 @Questor321 This is the repository for [gPodder.net](https://gpodder.net/) not the [gPodder application](https://gpodder.github.io/).  For the gPodder application is on GitHub at https://github.com/gpodder/gpodder/ so you should check issues there.

If you can give any background on how you ended up here (the "wrong place") we may be able to make changes to avoid such confusion in the future.

**Comment by LostPuppy24** [comment]
adamvoss, Thanks.  Let me see if I can recreate my steps.  Late now - will do so in the morning.

**Comment by LostPuppy24** [comment]
open gPodder app
under help - Go to gpodder.net
Login
Home tab shows "If you have problems, have a look at the docs or ask questions on the mailing list or forum."
Click on the "forum" link
Gets me here.

Hope this helps - LP24

**Comment by adamvoss** [comment]
Thanks LostPyppy24, it looks like some more explanation text could be added on that Home tab to explain what gPodder.net is and disambiguate it from the gPodder application.  I have also opened https://github.com/gpodder/gpodder/issues/355 on the gPodder side to try to help (I don't have a "Help" menu, but that could be a version thing).
