### ISSUE TITLE
Information about safety of subcription data.

### ISSUE THREAD

**Issue by Pagi-Maula** [gpodder/mygpo#702]
I wanted to know about how you handle the subscription data of your user who sign in to your services for syncronization? Is if kept safe enough?

**Comment by fundatillus** [comment]
This is a hobby project and we have no sponsors or other entities to answer to. Any and all data synced to gpodder.net stays on our two servers and goes nowhere else. 

mygpo is developed using well-established open source software and is kept up-to-date. 

Please send me an email at josh@fndtls.co to address any further concerns you may have.
