### ISSUE TITLE
Seeking maintainers?

### ISSUE THREAD

**Issue by garritfra** [gpodder/mygpo#703]
Hi!

I just saw your entry on the [Maintainers Wanted](https://github.com/pickhardt/maintainers-wanted) list. I just published a very similar project that's now looking for postings. If this project is still looking for maintainers, I'd greatly appreciate if you find some time to check out this project, and maybe add yours to the list.

Here's the link to the list:
https://seeking-maintainers.net

Thanks for your time!

**Comment by fundatillus** [comment]
Thanks, @garritfra! Just submitted our project.
