### ISSUE TITLE
ability to disable registrations

### ISSUE THREAD

**Issue by jelmer** [gpodder/mygpo#713]
I'm running my own instance of mygpo, but would like to disable registration from random internet users. It would be great if there was a configuration setting to disable new registrations.

**Comment by fundatillus** [comment]
As an open source project, we gladly accept PRs from the community.

**Comment by fundatillus** [comment]
Thinking more on this, registration is handled by Django and there are some ways out there to disable self-registration. Try searching for articles that explain how to accomplish this.

**Comment by uda** [comment]
Actually, registration is not handled by Django's builtin system, it is handled here https://github.com/gpodder/mygpo/blob/master/mygpo/users/views/registration.py#L69
It would be great to have more settings for the system internals
