### ISSUE TITLE
Feedback tab on website opens a loading screen, but doesn't deliver

### ISSUE THREAD

**Issue by FatStephen** [gpodder/mygpo#74]
![screen shot 10-22-17 at 01 52 am](https://user-images.githubusercontent.com/21272506/31858683-e2260a9a-b6cb-11e7-8022-16a72bb8e941.PNG)

RIP

**Comment by hovancik** [comment]
How could we reproduce this? I am able...

**Comment by stefankoegl** [comment]
The service that we have been using (getsatisfaction.com) does not provide a free service anymore, and seems to have changed its integration as well.

I will therefore remove it from gpodder.net

Thanks for reporting!

**Comment by stefankoegl** [comment]
Done
