### ISSUE TITLE
Can I avoid empty downloaded files?

### ISSUE THREAD

**Issue by RichardV22** [gpodder/mygpo#78]
When I check for new episodes and download them, in my PC's Downloads folder I get a file for every podcast programme on my list, whether or not a new podcast episode has been downloaded.  This makes it tedious to go through and find the new podcasts and delete the blank files (actually the 'blank files' contain a thumbnail link, which is irrelevant).
Can I avoid downloading the programme name as a folder when there is no new episode?

**Comment by stefankoegl** [comment]
Your question seems to be related to gPodder (and not to the website gpodder.net, which this repository is about). I have therefore moved your issue to gpodder/gpodder#513.
